//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.Communication.WpfService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        private WPF.Communication.WpfService.Department OfficeCategoryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public WPF.Communication.WpfService.Department OfficeCategory {
            get {
                return this.OfficeCategoryField;
            }
            set {
                if ((this.OfficeCategoryField.Equals(value) != true)) {
                    this.OfficeCategoryField = value;
                    this.RaisePropertyChanged("OfficeCategory");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Department", Namespace="http://tempuri.org/")]
    public enum Department : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        General = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IT = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Finance = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HR = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WpfService.WpfServiceSoap")]
    public interface WpfServiceSoap {
        
        // CODEGEN: Generating message contract since element name employee from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        WPF.Communication.WpfService.AddResponse Add(WPF.Communication.WpfService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<WPF.Communication.WpfService.AddResponse> AddAsync(WPF.Communication.WpfService.AddRequest request);
        
        // CODEGEN: Generating message contract since element name employeeBefore from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        WPF.Communication.WpfService.UpdateResponse Update(WPF.Communication.WpfService.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<WPF.Communication.WpfService.UpdateResponse> UpdateAsync(WPF.Communication.WpfService.UpdateRequest request);
        
        // CODEGEN: Generating message contract since element name employee from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Remove", ReplyAction="*")]
        WPF.Communication.WpfService.RemoveResponse Remove(WPF.Communication.WpfService.RemoveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Remove", ReplyAction="*")]
        System.Threading.Tasks.Task<WPF.Communication.WpfService.RemoveResponse> RemoveAsync(WPF.Communication.WpfService.RemoveRequest request);
        
        // CODEGEN: Generating message contract since element name LoadResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Load", ReplyAction="*")]
        WPF.Communication.WpfService.LoadResponse Load(WPF.Communication.WpfService.LoadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Load", ReplyAction="*")]
        System.Threading.Tasks.Task<WPF.Communication.WpfService.LoadResponse> LoadAsync(WPF.Communication.WpfService.LoadRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add", Namespace="http://tempuri.org/", Order=0)]
        public WPF.Communication.WpfService.AddRequestBody Body;
        
        public AddRequest() {
        }
        
        public AddRequest(WPF.Communication.WpfService.AddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WPF.Communication.WpfService.Employee employee;
        
        public AddRequestBody() {
        }
        
        public AddRequestBody(WPF.Communication.WpfService.Employee employee) {
            this.employee = employee;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddResponse", Namespace="http://tempuri.org/", Order=0)]
        public WPF.Communication.WpfService.AddResponseBody Body;
        
        public AddResponse() {
        }
        
        public AddResponse(WPF.Communication.WpfService.AddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddResult;
        
        public AddResponseBody() {
        }
        
        public AddResponseBody(int AddResult) {
            this.AddResult = AddResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public WPF.Communication.WpfService.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(WPF.Communication.WpfService.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WPF.Communication.WpfService.Employee employeeBefore;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public WPF.Communication.WpfService.Employee employeeAfter;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(WPF.Communication.WpfService.Employee employeeBefore, WPF.Communication.WpfService.Employee employeeAfter) {
            this.employeeBefore = employeeBefore;
            this.employeeAfter = employeeAfter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public WPF.Communication.WpfService.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(WPF.Communication.WpfService.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateResult;
        
        public UpdateResponseBody() {
        }
        
        public UpdateResponseBody(int UpdateResult) {
            this.UpdateResult = UpdateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Remove", Namespace="http://tempuri.org/", Order=0)]
        public WPF.Communication.WpfService.RemoveRequestBody Body;
        
        public RemoveRequest() {
        }
        
        public RemoveRequest(WPF.Communication.WpfService.RemoveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WPF.Communication.WpfService.Employee employee;
        
        public RemoveRequestBody() {
        }
        
        public RemoveRequestBody(WPF.Communication.WpfService.Employee employee) {
            this.employee = employee;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveResponse", Namespace="http://tempuri.org/", Order=0)]
        public WPF.Communication.WpfService.RemoveResponseBody Body;
        
        public RemoveResponse() {
        }
        
        public RemoveResponse(WPF.Communication.WpfService.RemoveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int RemoveResult;
        
        public RemoveResponseBody() {
        }
        
        public RemoveResponseBody(int RemoveResult) {
            this.RemoveResult = RemoveResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Load", Namespace="http://tempuri.org/", Order=0)]
        public WPF.Communication.WpfService.LoadRequestBody Body;
        
        public LoadRequest() {
        }
        
        public LoadRequest(WPF.Communication.WpfService.LoadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LoadRequestBody {
        
        public LoadRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadResponse", Namespace="http://tempuri.org/", Order=0)]
        public WPF.Communication.WpfService.LoadResponseBody Body;
        
        public LoadResponse() {
        }
        
        public LoadResponse(WPF.Communication.WpfService.LoadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WPF.Communication.WpfService.Employee[] LoadResult;
        
        public LoadResponseBody() {
        }
        
        public LoadResponseBody(WPF.Communication.WpfService.Employee[] LoadResult) {
            this.LoadResult = LoadResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WpfServiceSoapChannel : WPF.Communication.WpfService.WpfServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WpfServiceSoapClient : System.ServiceModel.ClientBase<WPF.Communication.WpfService.WpfServiceSoap>, WPF.Communication.WpfService.WpfServiceSoap {
        
        public WpfServiceSoapClient() {
        }
        
        public WpfServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WpfServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WpfServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WpfServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPF.Communication.WpfService.AddResponse WPF.Communication.WpfService.WpfServiceSoap.Add(WPF.Communication.WpfService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public int Add(WPF.Communication.WpfService.Employee employee) {
            WPF.Communication.WpfService.AddRequest inValue = new WPF.Communication.WpfService.AddRequest();
            inValue.Body = new WPF.Communication.WpfService.AddRequestBody();
            inValue.Body.employee = employee;
            WPF.Communication.WpfService.AddResponse retVal = ((WPF.Communication.WpfService.WpfServiceSoap)(this)).Add(inValue);
            return retVal.Body.AddResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WPF.Communication.WpfService.AddResponse> WPF.Communication.WpfService.WpfServiceSoap.AddAsync(WPF.Communication.WpfService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<WPF.Communication.WpfService.AddResponse> AddAsync(WPF.Communication.WpfService.Employee employee) {
            WPF.Communication.WpfService.AddRequest inValue = new WPF.Communication.WpfService.AddRequest();
            inValue.Body = new WPF.Communication.WpfService.AddRequestBody();
            inValue.Body.employee = employee;
            return ((WPF.Communication.WpfService.WpfServiceSoap)(this)).AddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPF.Communication.WpfService.UpdateResponse WPF.Communication.WpfService.WpfServiceSoap.Update(WPF.Communication.WpfService.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public int Update(WPF.Communication.WpfService.Employee employeeBefore, WPF.Communication.WpfService.Employee employeeAfter) {
            WPF.Communication.WpfService.UpdateRequest inValue = new WPF.Communication.WpfService.UpdateRequest();
            inValue.Body = new WPF.Communication.WpfService.UpdateRequestBody();
            inValue.Body.employeeBefore = employeeBefore;
            inValue.Body.employeeAfter = employeeAfter;
            WPF.Communication.WpfService.UpdateResponse retVal = ((WPF.Communication.WpfService.WpfServiceSoap)(this)).Update(inValue);
            return retVal.Body.UpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WPF.Communication.WpfService.UpdateResponse> WPF.Communication.WpfService.WpfServiceSoap.UpdateAsync(WPF.Communication.WpfService.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<WPF.Communication.WpfService.UpdateResponse> UpdateAsync(WPF.Communication.WpfService.Employee employeeBefore, WPF.Communication.WpfService.Employee employeeAfter) {
            WPF.Communication.WpfService.UpdateRequest inValue = new WPF.Communication.WpfService.UpdateRequest();
            inValue.Body = new WPF.Communication.WpfService.UpdateRequestBody();
            inValue.Body.employeeBefore = employeeBefore;
            inValue.Body.employeeAfter = employeeAfter;
            return ((WPF.Communication.WpfService.WpfServiceSoap)(this)).UpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPF.Communication.WpfService.RemoveResponse WPF.Communication.WpfService.WpfServiceSoap.Remove(WPF.Communication.WpfService.RemoveRequest request) {
            return base.Channel.Remove(request);
        }
        
        public int Remove(WPF.Communication.WpfService.Employee employee) {
            WPF.Communication.WpfService.RemoveRequest inValue = new WPF.Communication.WpfService.RemoveRequest();
            inValue.Body = new WPF.Communication.WpfService.RemoveRequestBody();
            inValue.Body.employee = employee;
            WPF.Communication.WpfService.RemoveResponse retVal = ((WPF.Communication.WpfService.WpfServiceSoap)(this)).Remove(inValue);
            return retVal.Body.RemoveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WPF.Communication.WpfService.RemoveResponse> WPF.Communication.WpfService.WpfServiceSoap.RemoveAsync(WPF.Communication.WpfService.RemoveRequest request) {
            return base.Channel.RemoveAsync(request);
        }
        
        public System.Threading.Tasks.Task<WPF.Communication.WpfService.RemoveResponse> RemoveAsync(WPF.Communication.WpfService.Employee employee) {
            WPF.Communication.WpfService.RemoveRequest inValue = new WPF.Communication.WpfService.RemoveRequest();
            inValue.Body = new WPF.Communication.WpfService.RemoveRequestBody();
            inValue.Body.employee = employee;
            return ((WPF.Communication.WpfService.WpfServiceSoap)(this)).RemoveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPF.Communication.WpfService.LoadResponse WPF.Communication.WpfService.WpfServiceSoap.Load(WPF.Communication.WpfService.LoadRequest request) {
            return base.Channel.Load(request);
        }
        
        public WPF.Communication.WpfService.Employee[] Load() {
            WPF.Communication.WpfService.LoadRequest inValue = new WPF.Communication.WpfService.LoadRequest();
            inValue.Body = new WPF.Communication.WpfService.LoadRequestBody();
            WPF.Communication.WpfService.LoadResponse retVal = ((WPF.Communication.WpfService.WpfServiceSoap)(this)).Load(inValue);
            return retVal.Body.LoadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WPF.Communication.WpfService.LoadResponse> WPF.Communication.WpfService.WpfServiceSoap.LoadAsync(WPF.Communication.WpfService.LoadRequest request) {
            return base.Channel.LoadAsync(request);
        }
        
        public System.Threading.Tasks.Task<WPF.Communication.WpfService.LoadResponse> LoadAsync() {
            WPF.Communication.WpfService.LoadRequest inValue = new WPF.Communication.WpfService.LoadRequest();
            inValue.Body = new WPF.Communication.WpfService.LoadRequestBody();
            return ((WPF.Communication.WpfService.WpfServiceSoap)(this)).LoadAsync(inValue);
        }
    }
}
